apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: service-mesh-og
  namespace: openshift-operators
spec:
  targetNamespaces:
    - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
spec:
  channel: stable
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: kiali-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
