apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./platform/mesh/operators.yaml
  - ./platform/mesh/smcp.yaml
  - ./platform/mesh/smmr.yaml
  - ./platform/mesh/peer-auth-mtls-strict.yaml
  - ./demo/ns-a.yaml
  - ./demo/ns-b.yaml
  - ./demo/app-a.yaml
  - ./demo/app-b.yaml
  - ./demo/allow-b-to-a.yaml
  - ./demo/traffic-generator.yaml
