apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/useCNI: "true"
    spec:
      serviceAccountName: app-b-sa
      containers:
        - name: app
          image: cgr.dev/chainguard/curl:latest
          command: ["sh","-c"]
          args: ["while true; do sleep 3600; done"]

