apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-sa
  namespace: ns-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-traffic-privileged
  namespace: ns-b
subjects:
  - kind: ServiceAccount
    name: traffic-sa
    namespace: ns-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged

